### ISSUE TITLE
Game never launches, launcher seems to have an issue with RAM.

### ISSUE THREAD

**Issue by NetGlitched** [TerrariaCraft/Launcher#1]
![image](https://user-images.githubusercontent.com/44915106/81581144-f807bc00-9373-11ea-9011-7360a9d76296.png)
Even at a low 3GB of RAM, the game will fail to launch. Says something about not being able to reserve enough space for an object heap. The highest I can go with the launcher still working is somewhere between 1 and 2 GB of RAM, which causes performance issues.

**Comment by Zeitheron** [comment]
Going to be fixed by embedding correct JVM.
